create table PROBLEMS_COST_SQL (
	ID_PRB      INTEGER NOT NULL,
	COST        FLOAT,
	DATE_UPDATE TIMESTAMP
);

COMMENT ON TABLE PROBLEMS_COST_SQL is 'Эталонная стоимость задач';
COMMENT ON COLUMN PROBLEMS_COST_SQL.ID_PRB is 'Идентификатор задачи';
COMMENT ON COLUMN PROBLEMS_COST_SQL.COST is 'Вычесленная оптимальная стоимость задачи';
COMMENT ON COLUMN PROBLEMS_COST_SQL.DATE_UPDATE is 'Дата обновления стоимости';

ALTER TABLE PROBLEMS_COST_SQL ADD FOREIGN KEY (ID_PRB) REFERENCES PROBLEMS (ID_PRB);

CREATE UNIQUE INDEX PRB_COST_IND ON PROBLEMS_COST_SQL (ID_PRB);

create table STATUS_COST_SQL (
	ID_STAT      INTEGER NOT NULL,
	COST        FLOAT,
	DATE_UPDATE TIMESTAMP
);

COMMENT ON TABLE STATUS_COST_SQL is 'Стоимость решения';
COMMENT ON COLUMN STATUS_COST_SQL.ID_STAT is 'Идентификатор решения';
COMMENT ON COLUMN STATUS_COST_SQL.COST is 'Стоимость решения';
COMMENT ON COLUMN STATUS_COST_SQL.DATE_UPDATE is 'Дата обновления стоимости';

ALTER TABLE STATUS_COST_SQL ADD FOREIGN KEY (ID_STAT) REFERENCES STATUS (ID_STAT);

CREATE UNIQUE INDEX STAT_COST_IND ON STATUS_COST_SQL (ID_STAT);